/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;
import jaco.mp3.player.MP3Player;
import java.awt.*; 
import javax.swing.*; 
import java.awt.event.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.TimerTask;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author DELL
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() throws FileNotFoundException, IOException {
        initComponents();
        p2.setVisible(false);
        p3.setVisible(false);
        Timer timer = new Timer();
        TimerTask task = new TimerTask(){
            private int i = 1;
            public void run(){
                if (i <= 300) {
                    ljb.setText("time : " +i+++"s");
                }
                else
                {
               JOptionPane.showMessageDialog(null, "time over", "Alert", JOptionPane.ERROR_MESSAGE);
                 timer.scheduleAtFixedRate(this, 0, 0);
                }
            }
        };
        timer.scheduleAtFixedRate(task, 0, 1000);
     String song="C:\\Users\\DELL\\Documents\\NetBeansProjects\\JavaApplication2\\music\\kahoot-lobby-music.mp3";
  try{
      MP3Player mp3=new MP3Player(new File(song));
      mp3.play();
  }
  catch(Exception e)
  {
      JOptionPane.showMessageDialog(null,"error");
  }        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        p = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        r1_2 = new javax.swing.JRadioButton();
        r2_2 = new javax.swing.JRadioButton();
        r3_2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        r1_3 = new javax.swing.JRadioButton();
        r2_3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        r1_4 = new javax.swing.JRadioButton();
        r2_4 = new javax.swing.JRadioButton();
        r3_4 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        r1_5 = new javax.swing.JRadioButton();
        r2_5 = new javax.swing.JRadioButton();
        r3_5 = new javax.swing.JRadioButton();
        btn1 = new javax.swing.JButton();
        ljb = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rn1 = new javax.swing.JRadioButton();
        rn2 = new javax.swing.JRadioButton();
        rn3 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rn1_2 = new javax.swing.JRadioButton();
        rn2_2 = new javax.swing.JRadioButton();
        rn3_2 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        rn1_3 = new javax.swing.JRadioButton();
        rn2_3 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        rn1_4 = new javax.swing.JRadioButton();
        rn2_4 = new javax.swing.JRadioButton();
        rn3_4 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        rn1_5 = new javax.swing.JRadioButton();
        rn2_5 = new javax.swing.JRadioButton();
        rn3_5 = new javax.swing.JRadioButton();
        btn2 = new javax.swing.JButton();
        p3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        rn3_1 = new javax.swing.JRadioButton();
        rn3_21 = new javax.swing.JRadioButton();
        rn3_3 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        rn3_11 = new javax.swing.JRadioButton();
        rn3_22 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        rn3_111 = new javax.swing.JRadioButton();
        rn3_222 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        rn3_44 = new javax.swing.JRadioButton();
        rn3_55 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        rn3_7 = new javax.swing.JRadioButton();
        rn3_777 = new javax.swing.JRadioButton();
        rn3_77 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("JAVA est un langage :");

        buttonGroup1.add(r1);
        r1.setText("Compilé");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(r2);
        r2.setText("Interprété");

        buttonGroup1.add(r3);
        r3.setText("Compilé et interpreté");

        jLabel2.setText("Toutes les classes héritent de la classe :");

        buttonGroup2.add(r1_2);
        r1_2.setText("Main");

        buttonGroup2.add(r2_2);
        r2_2.setText("object");
        r2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2_2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(r3_2);
        r3_2.setText("AWT");

        jLabel3.setText("Est-ce que on peut avoir plusieurs constructeurs pour la même classe  ");

        buttonGroup3.add(r1_3);
        r1_3.setText("oui");

        buttonGroup3.add(r2_3);
        r2_3.setText("non");

        jLabel4.setText("Par convention une classe   :");

        buttonGroup4.add(r1_4);
        r1_4.setText("est en minuscule");
        r1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1_4ActionPerformed(evt);
            }
        });

        buttonGroup4.add(r2_4);
        r2_4.setText("commence par une majuscule");

        buttonGroup4.add(r3_4);
        r3_4.setText("est en majuscules");

        jLabel5.setText("Dans la ligne public class A implements est  :");

        buttonGroup5.add(r1_5);
        r1_5.setText("Interface");

        buttonGroup5.add(r2_5);
        r2_5.setText("Classe parent");

        buttonGroup5.add(r3_5);
        r3_5.setText("Package");

        btn1.setText("suivant");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pLayout = new javax.swing.GroupLayout(p);
        p.setLayout(pLayout);
        pLayout.setHorizontalGroup(
            pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLayout.createSequentialGroup()
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(r1)
                        .addGap(99, 99, 99)
                        .addComponent(r2))
                    .addGroup(pLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(pLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(r1_2)
                        .addGap(57, 57, 57)
                        .addComponent(r2_2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r3_2)
                    .addComponent(r3))
                .addGap(76, 76, 76))
            .addGroup(pLayout.createSequentialGroup()
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(pLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(r1_3)
                        .addGap(53, 53, 53)
                        .addComponent(r2_3))
                    .addGroup(pLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(pLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(r1_4)
                        .addGap(40, 40, 40)
                        .addComponent(r2_4)
                        .addGap(30, 30, 30)
                        .addComponent(r3_4))
                    .addGroup(pLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pLayout.createSequentialGroup()
                                .addComponent(r1_5)
                                .addGap(68, 68, 68)
                                .addComponent(r2_5)
                                .addGap(99, 99, 99)
                                .addComponent(r3_5))
                            .addComponent(jLabel5))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn1)
                .addGap(74, 74, 74))
        );
        pLayout.setVerticalGroup(
            pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r1)
                    .addComponent(r2)
                    .addComponent(r3))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r1_2)
                    .addComponent(r2_2)
                    .addComponent(r3_2))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r1_3)
                    .addComponent(r2_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r1_4)
                    .addComponent(r2_4)
                    .addComponent(r3_4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r1_5)
                    .addComponent(r2_5)
                    .addComponent(r3_5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btn1)
                .addGap(34, 34, 34))
        );

        ljb.setText("time");

        jLabel6.setText("Après la compilation, un programme écrit en JAVA, il se transforme en programme en bytecode Quelle est l’extension du programme en \"bytecode ? :");

        buttonGroup6.add(rn1);
        rn1.setText("aucun des choix");

        buttonGroup6.add(rn2);
        rn2.setText(".JAVA");

        buttonGroup6.add(rn3);
        rn3.setText(".Class");

        jLabel7.setText("Class Test{Public Test () {System.out.println(”Bonjour”);}public Test (int i) {this();system.out.println(”Nous sommes en ”+i+ ” !”);};\\r\\n\"  }");

        buttonGroup7.add(rn1_2);
        rn1_2.setText("aucun des choix");

        buttonGroup7.add(rn2_2);
        rn2_2.setText("Bonjour Nous sommes en 2018 !");

        buttonGroup7.add(rn3_2);
        rn3_2.setText("Nous sommes en 2018 !");

        jLabel8.setText("Voici un constructeur de la classe Employee, y-at'il un problème ?Public void Employe(String n){Nom=n;}");

        buttonGroup8.add(rn1_3);
        rn1_3.setText("vrai");

        buttonGroup8.add(rn2_3);
        rn2_3.setText("faux");

        jLabel9.setText("Pour spécifier que la variable ne pourra plus être modifiée et doit être initialisée dès sa déclaration,on la déclare comme une constante avec le mot réservé");

        buttonGroup9.add(rn1_4);
        rn1_4.setText("aucun des choix");

        buttonGroup9.add(rn2_4);
        rn2_4.setText("final");

        buttonGroup9.add(rn3_4);
        rn3_4.setText("const");

        jLabel10.setText("Dans une classe, on accède à ses variables grâce au mot clé");

        buttonGroup9.add(rn1_5);
        rn1_5.setText("aucun des choix");

        buttonGroup9.add(rn2_5);
        rn2_5.setText("this");

        buttonGroup9.add(rn3_5);
        rn3_5.setText("super");

        btn2.setText("suivant");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(p2Layout.createSequentialGroup()
                                .addComponent(rn1)
                                .addGap(338, 338, 338)
                                .addComponent(rn2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rn3))
                            .addGroup(p2Layout.createSequentialGroup()
                                .addComponent(rn1_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rn2_2)
                                .addGap(178, 178, 178)
                                .addComponent(rn3_2)))
                        .addGap(72, 72, 72))
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(rn1_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rn2_3)
                        .addGap(388, 388, 388))
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1205, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(rn1_4)
                .addGap(255, 255, 255)
                .addComponent(rn2_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rn3_4)
                .addGap(123, 123, 123))
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(rn1_5)
                .addGap(249, 249, 249)
                .addComponent(rn2_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rn3_5)
                .addGap(170, 170, 170))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn2)
                .addGap(140, 140, 140))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rn1)
                    .addComponent(rn2)
                    .addComponent(rn3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rn2_2)
                    .addComponent(rn3_2)
                    .addComponent(rn1_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rn1_3)
                    .addComponent(rn2_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rn1_4)
                    .addComponent(rn2_4)
                    .addComponent(rn3_4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rn1_5)
                    .addComponent(rn2_5)
                    .addComponent(rn3_5))
                .addGap(28, 28, 28)
                .addComponent(btn2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setText("calculerSalaire(int) calculerSalaire(int, double)La méthode calculerSalaire est :");

        buttonGroup12.add(rn3_1);
        rn3_1.setText("aucun des choix");

        buttonGroup12.add(rn3_21);
        rn3_21.setText("surchargée");

        buttonGroup12.add(rn3_3);
        rn3_3.setText("redéfinie");

        jLabel12.setText("Une classe qui contient au moins une méthode abstraite doit être déclarée abstraite. :");

        buttonGroup13.add(rn3_11);
        rn3_11.setText("vrai");

        buttonGroup13.add(rn3_22);
        rn3_22.setText("faux");

        jLabel13.setText("Est-ce qu’une classe peut implémenter plusieurs interfaces ?");

        buttonGroup14.add(rn3_111);
        rn3_111.setText("vrai");

        buttonGroup14.add(rn3_222);
        rn3_222.setText("faux");

        jLabel14.setText("La déclaration d'une méthode suivante :public void traitement() throws IOException précise que la méthode propage une exception contrôlée");

        buttonGroup15.add(rn3_44);
        rn3_44.setText("vrai");

        buttonGroup15.add(rn3_55);
        rn3_55.setText("faux");

        jLabel15.setText("class Test{public static void main (String[] args) {try {int a =10;\"System.out.println (\\\"a = \\\" + a );int b = 0 / a;\"Systm.out.println (\\\"b = \\\" + b);}catch(ArithmeticException e){System.out.println (\\\"diviser par 0!\\\"); }finally{System.out.println (\\\"je suis à l’intérieur de finally\");}}}");

        buttonGroup16.add(rn3_7);
        rn3_7.setText("aucun des choix");

        buttonGroup16.add(rn3_777);
        rn3_777.setText("a=10 b=0 diviser par 0! je suis à l’intérieur de finally");

        buttonGroup16.add(rn3_77);
        rn3_77.setText("a=10 b=0 Je suis à l’intérieur de finally");

        jButton1.setText("suivant");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(p3Layout.createSequentialGroup()
                                .addComponent(rn3_1)
                                .addGap(200, 200, 200)
                                .addComponent(rn3_21)
                                .addGap(332, 332, 332)
                                .addComponent(rn3_3)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(p3Layout.createSequentialGroup()
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(p3Layout.createSequentialGroup()
                            .addComponent(rn3_111)
                            .addGap(292, 292, 292)
                            .addComponent(rn3_222))
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p3Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(rn3_11)
                                .addGap(292, 292, 292)
                                .addComponent(rn3_22))
                            .addGroup(p3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13))))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(rn3_44)
                        .addGap(292, 292, 292)
                        .addComponent(rn3_55))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 1534, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(rn3_7)
                        .addGap(227, 227, 227)
                        .addComponent(rn3_777)
                        .addGap(316, 316, 316)
                        .addComponent(rn3_77)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(609, 609, 609))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rn3_1)
                    .addComponent(rn3_21)
                    .addComponent(rn3_3))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rn3_11)
                    .addComponent(rn3_22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rn3_111)
                    .addComponent(rn3_222))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rn3_44)
                    .addComponent(rn3_55))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rn3_7)
                    .addComponent(rn3_777)
                    .addComponent(rn3_77))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ljb)
                .addGap(497, 497, 497))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ljb)
                .addGap(26, 26, 26)
                .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void r2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2_2ActionPerformed

    private void r1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1_4ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
 int score=0; 
				if(r3.isSelected()) {
		    		score=score+20;
		    		r3.setForeground(Color.GREEN);
		    	}
				 if(r2_2.isSelected()) {
					score=score+20;
					r2_2.setForeground(Color.GREEN);
				}
				 if(r1_3.isSelected()) {
					 score=score+20; 
					 r1_3.setForeground(Color.GREEN);
				 }
				 if(r2_4.isSelected()) {
					 score=score+20;
					 r2_4.setForeground(Color.GREEN);
				 }
				 if(r1_5.isSelected()) {
					 score=score+20;
					 r1_5.setForeground(Color.GREEN);
				 }
				 if(score>=40)
				 {
                                     p.setVisible(false);
				 p2.setVisible(true);
				 }
				 else {
			        JOptionPane.showMessageDialog(null, "vous ne pouver pas passer au niveau 2", "Alert", JOptionPane.ERROR_MESSAGE);
				 }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
       int score2 = 0;
					  if(rn3.isSelected()) {
				    		score2=score2+20;
				    		rn3.setForeground(Color.GREEN);
				    	}
						 if(rn2_2.isSelected()) {
							score2=score2+20;
							rn2_2.setForeground(Color.GREEN);
						}
						 if(rn2_3.isSelected()) {
							 score2=score2+20;
							 rn2_3.setForeground(Color.GREEN);
						 }
						 if(rn2_4.isSelected()) {
							 score2=score2+20;
							 rn2_4.setForeground(Color.GREEN);
						 }
						 if(rn2_5.isSelected()) {
							 score2=score2+20; 
							 rn2_5.setForeground(Color.GREEN);
						 }
                                                 if(score2>=60)
                                                 {
                                                  p2.setVisible(false);
				                  p3.setVisible(true);
                                                 }
                                                 else{
                                      	        JOptionPane.showMessageDialog(null, "vous ne pouver pas passer au niveau 2", "Alert", JOptionPane.ERROR_MESSAGE);

                                                 }

    }//GEN-LAST:event_btn2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 int score3 = 0;
						  if(rn3_21.isSelected()) {
					    		score3=score3+20;
					    		rn3_21.setForeground(Color.GREEN);
					    	}
							 if(rn3_11.isSelected()) {
								score3=score3+20;
								rn3_11.setForeground(Color.GREEN);
							}
							 if(rn3_222.isSelected()) {
								 score3=score3+20;
								 rn3_222.setForeground(Color.GREEN);
							 }
							 if(rn3_55.isSelected()) {
								 score3=score3+20;
								 rn3_55.setForeground(Color.GREEN);
							 }
							 if(rn3_77.isSelected()) {
								 score3=score3+20; 
								 rn3_77.setForeground(Color.GREEN);
							 }
                                                          if(score3>=80)
                                                 {
                                                          JOptionPane.showMessageDialog(null, "you win", "InfoBox: ",JOptionPane.INFORMATION_MESSAGE);
                                                 }
                                                 else{
                                      	        JOptionPane.showMessageDialog(null, "vous ne pouver pas passer au niveau 2", "Alert", JOptionPane.ERROR_MESSAGE);
                                                 }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NewJFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    public static javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel ljb;
    private javax.swing.JPanel p;
    public static javax.swing.JPanel p2;
    public static javax.swing.JPanel p3;
    public static javax.swing.JRadioButton r1;
    public static javax.swing.JRadioButton r1_2;
    public static javax.swing.JRadioButton r1_3;
    public static javax.swing.JRadioButton r1_4;
    public static javax.swing.JRadioButton r1_5;
    public static javax.swing.JRadioButton r2;
    public static javax.swing.JRadioButton r2_2;
    public static javax.swing.JRadioButton r2_3;
    public static javax.swing.JRadioButton r2_4;
    public static javax.swing.JRadioButton r2_5;
    public static javax.swing.JRadioButton r3;
    public static javax.swing.JRadioButton r3_2;
    public static javax.swing.JRadioButton r3_4;
    public static javax.swing.JRadioButton r3_5;
    public static javax.swing.JRadioButton rn1;
    public static javax.swing.JRadioButton rn1_2;
    public static javax.swing.JRadioButton rn1_3;
    public static javax.swing.JRadioButton rn1_4;
    public static javax.swing.JRadioButton rn1_5;
    public static javax.swing.JRadioButton rn2;
    public static javax.swing.JRadioButton rn2_2;
    public static javax.swing.JRadioButton rn2_3;
    public static javax.swing.JRadioButton rn2_4;
    public static javax.swing.JRadioButton rn2_5;
    public static javax.swing.JRadioButton rn3;
    public static javax.swing.JRadioButton rn3_1;
    public static javax.swing.JRadioButton rn3_11;
    public static javax.swing.JRadioButton rn3_111;
    public static javax.swing.JRadioButton rn3_2;
    public static javax.swing.JRadioButton rn3_21;
    public static javax.swing.JRadioButton rn3_22;
    public static javax.swing.JRadioButton rn3_222;
    public static javax.swing.JRadioButton rn3_3;
    public static javax.swing.JRadioButton rn3_4;
    public static javax.swing.JRadioButton rn3_44;
    public static javax.swing.JRadioButton rn3_5;
    public static javax.swing.JRadioButton rn3_55;
    public static javax.swing.JRadioButton rn3_7;
    public static javax.swing.JRadioButton rn3_77;
    public static javax.swing.JRadioButton rn3_777;
    // End of variables declaration//GEN-END:variables
}
